### PR TITLE
fix: fix PolarisCircuitBreakerConfiguration not clear when gateway invoke by wildcard apis

### LINKED ISSUE #1334: 用户使用通配API，API Path中带有大量可变成员时，会出现大量的内存占用
**Describe the bug**
同 https://github.com/polarismesh/polaris-java/issues/515

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

### PR DESCRIPTION
**Pull request by andrewshan**
## PR Type

Bugfix.

## Adding the issue link (#xxx) if possible.

closes #1334

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

## Checklist (Optional)

- [ ] Will pull request to branch of 2023.
- [ ] Will pull request to branch of 2022.
- [ ] Will pull request to branch of 2021.
- [ ] Will pull request to branch of 2020.
- [x] Will pull request to branch of hoxton.

### CODE REVIEW

File: spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/config/PolarisCircuitBreakerProperties.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+	/**
+	 * Whether enable polaris circuit-breaker function.
+	 */
+	@Value("${spring.cloud.polaris.circuitbreaker.enabled:#{true}}")
+	private boolean enabled = true;
+
+	/**
+	 * Interval to clean up PolarisCircuitBreakerConfiguration, unit millisecond.
+	 */
+	@Value("${spring.cloud.polaris.circuitbreaker.configuration-expire-interval:#{300000}}")
```
Comment (SkyeBeFreeman) [inline spring-cloud-starter-tencent-polaris-circuitbreaker/src/main/java/com/tencent/cloud/polaris/circuitbreaker/config/PolarisCircuitBreakerProperties.java]: value和变量名需保持一致

**Review by SkyeBeFreeman — CHANGES_REQUESTED** [review]

**Review by SkyeBeFreeman — APPROVED** [review]
