### PR TITLE
shutdown server when connect to config server failed

### LINKED ISSUE #493: Spring Cloud Tencent Config 链接的远程主机无法打开时未显示标注出错误
**Describe the bug**

官方给的 polaris 地址是这个

> Console Address : http://14.116.241.63:8080/
Username: polaris
Password: polaris
Server Address: grpc://183.47.111.80:8091
The example addresses under spring-cloud-tencent-example all point to the experience service address (grpc://183.47.111.80:8091) by default. If you only experience Spring Cloud Tencent, you can run any example directly with one click.

官方提供的 polaris-config-example demo 的 `bootstrap.yml` 是这个
```yml
server:
  port: 48084
spring:
  application:
    name: polaris-config-example
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      config:
        auto-refresh: true # auto refresh when config file changed
        groups:
          - name: ${spring.application.name} # group name
            files: [ "config/application.properties", "config/bootstrap.yml" ] # config/application.properties takes precedence over config/bootstrap.yml
        refresh-behavior: specific_bean
management:
  endpoints:
    web:
      exposure:
        include:
          - polaris-config

```
我调整了 polaris 的 properties 文件的内容
```
server.port=11111
```
image

此时配置项是正常的.
问题1. 当我将地址从 `grpc://183.47.111.80:8091` 调整为 `grpc://111.111.111.111:111` . 很明显 该 ip无法访问, 启动时应该提示报错.
然而应用启动时正常的, 启动日志是这样的
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.3.12.RELEASE)

2022-08-05 10:30:54.966  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='application.properties'}
2022-08-05 10:31:06.971  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='application.yml'}
2022-08-05 10:31:15.001  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='bootstrap.properties'}
2022-08-05 10:31:26.010  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='bootstrap.yml'}
2022-08-05 10:31:33.028  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file success. namespace = default, group = polaris-config-example, fileName = config/application.properties
2022-08-05 10:31:43.110  INFO 71390 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file success. namespace = default, group = polaris-config-example, fileName = config/bootstrap.yml
2022-08-05 10:31:43.113  INFO 71390 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-application.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-application.yml'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-bootstrap.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-bootstrap.yml'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-config/application.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-config/bootstrap.yml'}]
2022-08-05 10:31:43.117  INFO 71390 --- [           main] .c.p.c.e.PolarisConfigExampleApplication : No active profile set, falling back to default profiles: default
2022-08-05 10:31:43.363  WARN 71390 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'polaris-metadata' contains invalid characters, please migrate to a valid format.
2022-08-05 10:31:43.368  WARN 71390 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'polaris-config' contains invalid characters, please migrate to a valid format.
2022-08-05 10:31:43.533  INFO 71390 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=f48492e2-2530-3f9c-9c0b-791505a95396
2022-08-05 10:31:43.689  INFO 71390 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 48084 (http)
2022-08-05 10:31:43.695  INFO 71390 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-05 10:31:43.695  INFO 71390 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2022-08-05 10:31:43.758  INFO 71390 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-05 10:31:43.758  INFO 71390 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 633 ms
2022-08-05 10:31:43.973  INFO 71390 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-08-05 10:31:44.044  INFO 71390 --- [           main] c.t.c.c.metadata.StaticMetadataManager   : [SCT] Loaded static metadata info. StaticMetadataManager{envMetadata={}, envTransitiveMetadata={}, configMetadata={}, configTransitiveMetadata={}, customSPIMetadata={}, customSPITransitiveMetadata={}, mergedStaticMetadata={}, mergedStaticTransitiveMetadata={}, zone='null', region='null', campus='null'}
2022-08-05 10:31:44.197  INFO 71390 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: SPRING_UTIL_TIMEOUT_SEC, beanName: inetUtilsProperties, field: org.springframework.cloud.commons.util.InetUtilsProperties.timeoutSeconds
2022-08-05 10:31:44.197  INFO 71390 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: spring.util.timeout.sec, beanName: inetUtilsProperties, field: org.springframework.cloud.commons.util.InetUtilsProperties.timeoutSeconds
2022-08-05 10:31:44.223  INFO 71390 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-08-05 10:31:44.275  INFO 71390 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 48084 (http) with context path ''
2022-08-05 10:31:44.283  INFO 71390 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: timeout, beanName: scopedTarget.configController, field: com.tencent.cloud.polaris.config.example.ConfigController.timeout
2022-08-05 10:31:44.292  INFO 71390 --- [           main] .c.p.c.e.PolarisConfigExampleApplication : Started PolarisConfigExampleApplication in 69.658 seconds (JVM running for 70.227)
2022-08-05 10:31:44.576  INFO 71390 --- [(2)-10.45.18.74] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-05 10:31:44.576  INFO 71390 --- [(2)-10.45.18.74] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-05 10:31:44.580  INFO 71390 --- [(2)-10.45.18.74] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
```

问题2. 当我将地址从 `grpc://183.47.111.80:8091` 调整为 `grpc://183.47.111.80:1111` . 很明显该端口无法访问, 启动时应该提示报错.
然而应用启动时正常的, 并且正常加载了 ` grpc://183.47.111.80:8091` 时的配置(server.port=11111)  启动日志是这样的
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.3.12.RELEASE)

2022-08-05 10:35:20.311  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='application.properties'}
2022-08-05 10:35:20.389  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='application.yml'}
2022-08-05 10:35:20.472  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='bootstrap.properties'}
2022-08-05 10:35:20.549  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file. file = ConfigFile{namespace='default', fileGroup='polaris-config-example', fileName='bootstrap.yml'}
2022-08-05 10:35:20.620  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file success. namespace = default, group = polaris-config-example, fileName = config/application.properties
2022-08-05 10:35:20.684  INFO 74896 --- [           main] c.t.c.p.c.a.PolarisConfigFileLocator     : [SCT Config] Load and inject polaris config file success. namespace = default, group = polaris-config-example, fileName = config/bootstrap.yml
2022-08-05 10:35:20.684  INFO 74896 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-application.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-application.yml'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-bootstrap.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-bootstrap.yml'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-config/application.properties'}, BootstrapPropertySource {name='bootstrapProperties-default-polaris-config-example-config/bootstrap.yml'}]
2022-08-05 10:35:20.688  INFO 74896 --- [           main] .c.p.c.e.PolarisConfigExampleApplication : No active profile set, falling back to default profiles: default
2022-08-05 10:35:20.951  WARN 74896 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'polaris-metadata' contains invalid characters, please migrate to a valid format.
2022-08-05 10:35:20.957  WARN 74896 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'polaris-config' contains invalid characters, please migrate to a valid format.
2022-08-05 10:35:21.116  INFO 74896 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=f48492e2-2530-3f9c-9c0b-791505a95396
2022-08-05 10:35:21.272  INFO 74896 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 11111 (http)
2022-08-05 10:35:21.277  INFO 74896 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-05 10:35:21.277  INFO 74896 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2022-08-05 10:35:21.337  INFO 74896 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-05 10:35:21.337  INFO 74896 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 639 ms
2022-08-05 10:35:21.552  INFO 74896 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-08-05 10:35:21.626  INFO 74896 --- [           main] c.t.c.c.metadata.StaticMetadataManager   : [SCT] Loaded static metadata info. StaticMetadataManager{envMetadata={}, envTransitiveMetadata={}, configMetadata={}, configTransitiveMetadata={}, customSPIMetadata={}, customSPITransitiveMetadata={}, mergedStaticMetadata={}, mergedStaticTransitiveMetadata={}, zone='null', region='null', campus='null'}
2022-08-05 10:35:21.775  INFO 74896 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: SPRING_UTIL_TIMEOUT_SEC, beanName: inetUtilsProperties, field: org.springframework.cloud.commons.util.InetUtilsProperties.timeoutSeconds
2022-08-05 10:35:21.775  INFO 74896 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: spring.util.timeout.sec, beanName: inetUtilsProperties, field: org.springframework.cloud.commons.util.InetUtilsProperties.timeoutSeconds
2022-08-05 10:35:21.802  INFO 74896 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-08-05 10:35:21.857  INFO 74896 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 11111 (http) with context path ''
2022-08-05 10:35:21.862  INFO 74896 --- [           main] c.t.c.p.c.s.a.SpringValueProcessor       : Monitoring key: timeout, beanName: scopedTarget.configController, field: com.tencent.cloud.polaris.config.example.ConfigController.timeout
2022-08-05 10:35:21.871  INFO 74896 --- [           main] .c.p.c.e.PolarisConfigExampleApplication : Started PolarisConfigExampleApplication in 3.046 seconds (JVM running for 3.619)
2022-08-05 10:35:22.072  INFO 74896 --- [(1)-10.45.18.74] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-05 10:35:22.072  INFO 74896 --- [(1)-10.45.18.74] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-05 10:35:22.077  INFO 74896 --- [(1)-10.45.18.74] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
```

**To Reproduce**
见描述

**Expected behavior**
当问题 1 和问题2 中的配置变更无法访问时, 应显著表示出错误日志表述出错误产生的原因, 而不是提供一个隐式的解决方法

**Environment**
- Version: [1.7.0-Hoxton.SR12 ]
- OS: [MACOS 11.0 ]

**Additional context**

### PR DESCRIPTION
**Pull request by lepdou**
## Adding the issue link (#xxx) if possible.

fix #493 

## Checklist

- [ ] Add copyright holder at the beginning of .class file if it is new.
- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

### CODE REVIEW

File: spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/AddressUtils.java [hunk 1]
```diff
@@ -49,4 +53,23 @@ public static List<String> parseAddressList(String addressInfo) {
...
+		}
+		catch (IOException e) {
+			return false;
+		}
+		finally {
+			try {
+				socket.close();
+			}
+			catch (IOException e) {
+				e.printStackTrace();
```
Comment (SkyeBeFreeman) [inline spring-cloud-tencent-commons/src/main/java/com/tencent/cloud/common/util/AddressUtils.java:70]: Use LOGGER to print.

**Review by SkyeBeFreeman — CHANGES_REQUESTED** [review]

File: spring-cloud-tencent-plugin-starters/spring-cloud-tencent-pushgateway-plugin/pom.xml [hunk 2]
```diff
@@ -13,9 +13,20 @@
 	<artifactId>spring-cloud-tencent-pushgateway-plugin</artifactId>
 
 	<dependencies>
+		<dependency>
```
Comment (SkyeBeFreeman) [inline spring-cloud-tencent-plugin-starters/spring-cloud-tencent-pushgateway-plugin/pom.xml:16]: 这里恢复原样吧，我在 polaris-java 处理这个问题

**Review by SkyeBeFreeman — CHANGES_REQUESTED** [review]

**Review by SkyeBeFreeman — APPROVED** [review]
